// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consumer.proto

package com.prod.app.protobuff;

public final class Consumer {
  private Consumer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConsumerPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.ConsumerPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    boolean hasDbInfo();
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    com.prod.app.protobuff.Entity.EntityPb getDbInfo();
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    com.prod.app.protobuff.Names.NamesPb getName();
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    boolean hasContactDetails();
    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    com.prod.app.protobuff.Contactdetails.ContactDetailsPb getContactDetails();
    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder getContactDetailsOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    boolean hasDob();
    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    com.prod.app.protobuff.Time.TimePb getDob();
    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    com.prod.app.protobuff.Time.TimePbOrBuilder getDobOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    boolean hasGender();
    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    com.prod.app.protobuff.Gender.GenderPb getGender();
    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    com.prod.app.protobuff.Gender.GenderPbOrBuilder getGenderOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    boolean hasAddress();
    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    com.prod.app.protobuff.Address.AddressPb getAddress();
    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    com.prod.app.protobuff.Address.AddressPbOrBuilder getAddressOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    boolean hasType();
    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    com.prod.app.protobuff.Persontypeenum.PersonTypePb getType();
    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder getTypeOrBuilder();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.ConsumerPb}
   */
  public  static final class ConsumerPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.ConsumerPb)
      ConsumerPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConsumerPb.newBuilder() to construct.
    private ConsumerPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConsumerPb() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConsumerPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConsumerPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.prod.app.protobuff.Entity.EntityPb.Builder subBuilder = null;
              if (dbInfo_ != null) {
                subBuilder = dbInfo_.toBuilder();
              }
              dbInfo_ = input.readMessage(com.prod.app.protobuff.Entity.EntityPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dbInfo_);
                dbInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.prod.app.protobuff.Names.NamesPb.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(com.prod.app.protobuff.Names.NamesPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder subBuilder = null;
              if (contactDetails_ != null) {
                subBuilder = contactDetails_.toBuilder();
              }
              contactDetails_ = input.readMessage(com.prod.app.protobuff.Contactdetails.ContactDetailsPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contactDetails_);
                contactDetails_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.prod.app.protobuff.Time.TimePb.Builder subBuilder = null;
              if (dob_ != null) {
                subBuilder = dob_.toBuilder();
              }
              dob_ = input.readMessage(com.prod.app.protobuff.Time.TimePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dob_);
                dob_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.prod.app.protobuff.Gender.GenderPb.Builder subBuilder = null;
              if (gender_ != null) {
                subBuilder = gender_.toBuilder();
              }
              gender_ = input.readMessage(com.prod.app.protobuff.Gender.GenderPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gender_);
                gender_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.prod.app.protobuff.Address.AddressPb.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.prod.app.protobuff.Address.AddressPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder subBuilder = null;
              if (type_ != null) {
                subBuilder = type_.toBuilder();
              }
              type_ = input.readMessage(com.prod.app.protobuff.Persontypeenum.PersonTypePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(type_);
                type_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Consumer.ConsumerPb.class, com.prod.app.protobuff.Consumer.ConsumerPb.Builder.class);
    }

    public static final int DBINFO_FIELD_NUMBER = 1;
    private com.prod.app.protobuff.Entity.EntityPb dbInfo_;
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public boolean hasDbInfo() {
      return dbInfo_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public com.prod.app.protobuff.Entity.EntityPb getDbInfo() {
      return dbInfo_ == null ? com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
    }
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder() {
      return getDbInfo();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.prod.app.protobuff.Names.NamesPb name_;
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public com.prod.app.protobuff.Names.NamesPb getName() {
      return name_ == null ? com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
    }
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder() {
      return getName();
    }

    public static final int CONTACTDETAILS_FIELD_NUMBER = 3;
    private com.prod.app.protobuff.Contactdetails.ContactDetailsPb contactDetails_;
    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    public boolean hasContactDetails() {
      return contactDetails_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    public com.prod.app.protobuff.Contactdetails.ContactDetailsPb getContactDetails() {
      return contactDetails_ == null ? com.prod.app.protobuff.Contactdetails.ContactDetailsPb.getDefaultInstance() : contactDetails_;
    }
    /**
     * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
     */
    public com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder getContactDetailsOrBuilder() {
      return getContactDetails();
    }

    public static final int DOB_FIELD_NUMBER = 4;
    private com.prod.app.protobuff.Time.TimePb dob_;
    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    public boolean hasDob() {
      return dob_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    public com.prod.app.protobuff.Time.TimePb getDob() {
      return dob_ == null ? com.prod.app.protobuff.Time.TimePb.getDefaultInstance() : dob_;
    }
    /**
     * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
     */
    public com.prod.app.protobuff.Time.TimePbOrBuilder getDobOrBuilder() {
      return getDob();
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private com.prod.app.protobuff.Gender.GenderPb gender_;
    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    public boolean hasGender() {
      return gender_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    public com.prod.app.protobuff.Gender.GenderPb getGender() {
      return gender_ == null ? com.prod.app.protobuff.Gender.GenderPb.getDefaultInstance() : gender_;
    }
    /**
     * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
     */
    public com.prod.app.protobuff.Gender.GenderPbOrBuilder getGenderOrBuilder() {
      return getGender();
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private com.prod.app.protobuff.Address.AddressPb address_;
    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    public com.prod.app.protobuff.Address.AddressPb getAddress() {
      return address_ == null ? com.prod.app.protobuff.Address.AddressPb.getDefaultInstance() : address_;
    }
    /**
     * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
     */
    public com.prod.app.protobuff.Address.AddressPbOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private com.prod.app.protobuff.Persontypeenum.PersonTypePb type_;
    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    public boolean hasType() {
      return type_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    public com.prod.app.protobuff.Persontypeenum.PersonTypePb getType() {
      return type_ == null ? com.prod.app.protobuff.Persontypeenum.PersonTypePb.getDefaultInstance() : type_;
    }
    /**
     * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
     */
    public com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder getTypeOrBuilder() {
      return getType();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dbInfo_ != null) {
        output.writeMessage(1, getDbInfo());
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      if (contactDetails_ != null) {
        output.writeMessage(3, getContactDetails());
      }
      if (dob_ != null) {
        output.writeMessage(4, getDob());
      }
      if (gender_ != null) {
        output.writeMessage(5, getGender());
      }
      if (address_ != null) {
        output.writeMessage(6, getAddress());
      }
      if (type_ != null) {
        output.writeMessage(8, getType());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dbInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDbInfo());
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      if (contactDetails_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getContactDetails());
      }
      if (dob_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getDob());
      }
      if (gender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getGender());
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getAddress());
      }
      if (type_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getType());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Consumer.ConsumerPb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Consumer.ConsumerPb other = (com.prod.app.protobuff.Consumer.ConsumerPb) obj;

      if (hasDbInfo() != other.hasDbInfo()) return false;
      if (hasDbInfo()) {
        if (!getDbInfo()
            .equals(other.getDbInfo())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasContactDetails() != other.hasContactDetails()) return false;
      if (hasContactDetails()) {
        if (!getContactDetails()
            .equals(other.getContactDetails())) return false;
      }
      if (hasDob() != other.hasDob()) return false;
      if (hasDob()) {
        if (!getDob()
            .equals(other.getDob())) return false;
      }
      if (hasGender() != other.hasGender()) return false;
      if (hasGender()) {
        if (!getGender()
            .equals(other.getGender())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDbInfo()) {
        hash = (37 * hash) + DBINFO_FIELD_NUMBER;
        hash = (53 * hash) + getDbInfo().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasContactDetails()) {
        hash = (37 * hash) + CONTACTDETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getContactDetails().hashCode();
      }
      if (hasDob()) {
        hash = (37 * hash) + DOB_FIELD_NUMBER;
        hash = (53 * hash) + getDob().hashCode();
      }
      if (hasGender()) {
        hash = (37 * hash) + GENDER_FIELD_NUMBER;
        hash = (53 * hash) + getGender().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Consumer.ConsumerPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.ConsumerPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.ConsumerPb)
        com.prod.app.protobuff.Consumer.ConsumerPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Consumer.ConsumerPb.class, com.prod.app.protobuff.Consumer.ConsumerPb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Consumer.ConsumerPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dbInfoBuilder_ == null) {
          dbInfo_ = null;
        } else {
          dbInfo_ = null;
          dbInfoBuilder_ = null;
        }
        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        if (contactDetailsBuilder_ == null) {
          contactDetails_ = null;
        } else {
          contactDetails_ = null;
          contactDetailsBuilder_ = null;
        }
        if (dobBuilder_ == null) {
          dob_ = null;
        } else {
          dob_ = null;
          dobBuilder_ = null;
        }
        if (genderBuilder_ == null) {
          gender_ = null;
        } else {
          gender_ = null;
          genderBuilder_ = null;
        }
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        if (typeBuilder_ == null) {
          type_ = null;
        } else {
          type_ = null;
          typeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Consumer.ConsumerPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPb build() {
        com.prod.app.protobuff.Consumer.ConsumerPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPb buildPartial() {
        com.prod.app.protobuff.Consumer.ConsumerPb result = new com.prod.app.protobuff.Consumer.ConsumerPb(this);
        if (dbInfoBuilder_ == null) {
          result.dbInfo_ = dbInfo_;
        } else {
          result.dbInfo_ = dbInfoBuilder_.build();
        }
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        if (contactDetailsBuilder_ == null) {
          result.contactDetails_ = contactDetails_;
        } else {
          result.contactDetails_ = contactDetailsBuilder_.build();
        }
        if (dobBuilder_ == null) {
          result.dob_ = dob_;
        } else {
          result.dob_ = dobBuilder_.build();
        }
        if (genderBuilder_ == null) {
          result.gender_ = gender_;
        } else {
          result.gender_ = genderBuilder_.build();
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        if (typeBuilder_ == null) {
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Consumer.ConsumerPb) {
          return mergeFrom((com.prod.app.protobuff.Consumer.ConsumerPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Consumer.ConsumerPb other) {
        if (other == com.prod.app.protobuff.Consumer.ConsumerPb.getDefaultInstance()) return this;
        if (other.hasDbInfo()) {
          mergeDbInfo(other.getDbInfo());
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        if (other.hasContactDetails()) {
          mergeContactDetails(other.getContactDetails());
        }
        if (other.hasDob()) {
          mergeDob(other.getDob());
        }
        if (other.hasGender()) {
          mergeGender(other.getGender());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        if (other.hasType()) {
          mergeType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Consumer.ConsumerPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Consumer.ConsumerPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.prod.app.protobuff.Entity.EntityPb dbInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder> dbInfoBuilder_;
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public boolean hasDbInfo() {
        return dbInfoBuilder_ != null || dbInfo_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPb getDbInfo() {
        if (dbInfoBuilder_ == null) {
          return dbInfo_ == null ? com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
        } else {
          return dbInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder setDbInfo(com.prod.app.protobuff.Entity.EntityPb value) {
        if (dbInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dbInfo_ = value;
          onChanged();
        } else {
          dbInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder setDbInfo(
          com.prod.app.protobuff.Entity.EntityPb.Builder builderForValue) {
        if (dbInfoBuilder_ == null) {
          dbInfo_ = builderForValue.build();
          onChanged();
        } else {
          dbInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder mergeDbInfo(com.prod.app.protobuff.Entity.EntityPb value) {
        if (dbInfoBuilder_ == null) {
          if (dbInfo_ != null) {
            dbInfo_ =
              com.prod.app.protobuff.Entity.EntityPb.newBuilder(dbInfo_).mergeFrom(value).buildPartial();
          } else {
            dbInfo_ = value;
          }
          onChanged();
        } else {
          dbInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder clearDbInfo() {
        if (dbInfoBuilder_ == null) {
          dbInfo_ = null;
          onChanged();
        } else {
          dbInfo_ = null;
          dbInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPb.Builder getDbInfoBuilder() {
        
        onChanged();
        return getDbInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder() {
        if (dbInfoBuilder_ != null) {
          return dbInfoBuilder_.getMessageOrBuilder();
        } else {
          return dbInfo_ == null ?
              com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder> 
          getDbInfoFieldBuilder() {
        if (dbInfoBuilder_ == null) {
          dbInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder>(
                  getDbInfo(),
                  getParentForChildren(),
                  isClean());
          dbInfo_ = null;
        }
        return dbInfoBuilder_;
      }

      private com.prod.app.protobuff.Names.NamesPb name_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder> nameBuilder_;
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPb getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder setName(com.prod.app.protobuff.Names.NamesPb value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder setName(
          com.prod.app.protobuff.Names.NamesPb.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder mergeName(com.prod.app.protobuff.Names.NamesPb value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              com.prod.app.protobuff.Names.NamesPb.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPb.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }

      private com.prod.app.protobuff.Contactdetails.ContactDetailsPb contactDetails_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Contactdetails.ContactDetailsPb, com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder, com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder> contactDetailsBuilder_;
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public boolean hasContactDetails() {
        return contactDetailsBuilder_ != null || contactDetails_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPb getContactDetails() {
        if (contactDetailsBuilder_ == null) {
          return contactDetails_ == null ? com.prod.app.protobuff.Contactdetails.ContactDetailsPb.getDefaultInstance() : contactDetails_;
        } else {
          return contactDetailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public Builder setContactDetails(com.prod.app.protobuff.Contactdetails.ContactDetailsPb value) {
        if (contactDetailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contactDetails_ = value;
          onChanged();
        } else {
          contactDetailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public Builder setContactDetails(
          com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder builderForValue) {
        if (contactDetailsBuilder_ == null) {
          contactDetails_ = builderForValue.build();
          onChanged();
        } else {
          contactDetailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public Builder mergeContactDetails(com.prod.app.protobuff.Contactdetails.ContactDetailsPb value) {
        if (contactDetailsBuilder_ == null) {
          if (contactDetails_ != null) {
            contactDetails_ =
              com.prod.app.protobuff.Contactdetails.ContactDetailsPb.newBuilder(contactDetails_).mergeFrom(value).buildPartial();
          } else {
            contactDetails_ = value;
          }
          onChanged();
        } else {
          contactDetailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public Builder clearContactDetails() {
        if (contactDetailsBuilder_ == null) {
          contactDetails_ = null;
          onChanged();
        } else {
          contactDetails_ = null;
          contactDetailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder getContactDetailsBuilder() {
        
        onChanged();
        return getContactDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder getContactDetailsOrBuilder() {
        if (contactDetailsBuilder_ != null) {
          return contactDetailsBuilder_.getMessageOrBuilder();
        } else {
          return contactDetails_ == null ?
              com.prod.app.protobuff.Contactdetails.ContactDetailsPb.getDefaultInstance() : contactDetails_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.ContactDetailsPb contactDetails = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Contactdetails.ContactDetailsPb, com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder, com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder> 
          getContactDetailsFieldBuilder() {
        if (contactDetailsBuilder_ == null) {
          contactDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Contactdetails.ContactDetailsPb, com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder, com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder>(
                  getContactDetails(),
                  getParentForChildren(),
                  isClean());
          contactDetails_ = null;
        }
        return contactDetailsBuilder_;
      }

      private com.prod.app.protobuff.Time.TimePb dob_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Time.TimePb, com.prod.app.protobuff.Time.TimePb.Builder, com.prod.app.protobuff.Time.TimePbOrBuilder> dobBuilder_;
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public boolean hasDob() {
        return dobBuilder_ != null || dob_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public com.prod.app.protobuff.Time.TimePb getDob() {
        if (dobBuilder_ == null) {
          return dob_ == null ? com.prod.app.protobuff.Time.TimePb.getDefaultInstance() : dob_;
        } else {
          return dobBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public Builder setDob(com.prod.app.protobuff.Time.TimePb value) {
        if (dobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dob_ = value;
          onChanged();
        } else {
          dobBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public Builder setDob(
          com.prod.app.protobuff.Time.TimePb.Builder builderForValue) {
        if (dobBuilder_ == null) {
          dob_ = builderForValue.build();
          onChanged();
        } else {
          dobBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public Builder mergeDob(com.prod.app.protobuff.Time.TimePb value) {
        if (dobBuilder_ == null) {
          if (dob_ != null) {
            dob_ =
              com.prod.app.protobuff.Time.TimePb.newBuilder(dob_).mergeFrom(value).buildPartial();
          } else {
            dob_ = value;
          }
          onChanged();
        } else {
          dobBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public Builder clearDob() {
        if (dobBuilder_ == null) {
          dob_ = null;
          onChanged();
        } else {
          dob_ = null;
          dobBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public com.prod.app.protobuff.Time.TimePb.Builder getDobBuilder() {
        
        onChanged();
        return getDobFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      public com.prod.app.protobuff.Time.TimePbOrBuilder getDobOrBuilder() {
        if (dobBuilder_ != null) {
          return dobBuilder_.getMessageOrBuilder();
        } else {
          return dob_ == null ?
              com.prod.app.protobuff.Time.TimePb.getDefaultInstance() : dob_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.TimePb dob = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Time.TimePb, com.prod.app.protobuff.Time.TimePb.Builder, com.prod.app.protobuff.Time.TimePbOrBuilder> 
          getDobFieldBuilder() {
        if (dobBuilder_ == null) {
          dobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Time.TimePb, com.prod.app.protobuff.Time.TimePb.Builder, com.prod.app.protobuff.Time.TimePbOrBuilder>(
                  getDob(),
                  getParentForChildren(),
                  isClean());
          dob_ = null;
        }
        return dobBuilder_;
      }

      private com.prod.app.protobuff.Gender.GenderPb gender_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Gender.GenderPb, com.prod.app.protobuff.Gender.GenderPb.Builder, com.prod.app.protobuff.Gender.GenderPbOrBuilder> genderBuilder_;
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public boolean hasGender() {
        return genderBuilder_ != null || gender_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public com.prod.app.protobuff.Gender.GenderPb getGender() {
        if (genderBuilder_ == null) {
          return gender_ == null ? com.prod.app.protobuff.Gender.GenderPb.getDefaultInstance() : gender_;
        } else {
          return genderBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public Builder setGender(com.prod.app.protobuff.Gender.GenderPb value) {
        if (genderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gender_ = value;
          onChanged();
        } else {
          genderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public Builder setGender(
          com.prod.app.protobuff.Gender.GenderPb.Builder builderForValue) {
        if (genderBuilder_ == null) {
          gender_ = builderForValue.build();
          onChanged();
        } else {
          genderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public Builder mergeGender(com.prod.app.protobuff.Gender.GenderPb value) {
        if (genderBuilder_ == null) {
          if (gender_ != null) {
            gender_ =
              com.prod.app.protobuff.Gender.GenderPb.newBuilder(gender_).mergeFrom(value).buildPartial();
          } else {
            gender_ = value;
          }
          onChanged();
        } else {
          genderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public Builder clearGender() {
        if (genderBuilder_ == null) {
          gender_ = null;
          onChanged();
        } else {
          gender_ = null;
          genderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public com.prod.app.protobuff.Gender.GenderPb.Builder getGenderBuilder() {
        
        onChanged();
        return getGenderFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      public com.prod.app.protobuff.Gender.GenderPbOrBuilder getGenderOrBuilder() {
        if (genderBuilder_ != null) {
          return genderBuilder_.getMessageOrBuilder();
        } else {
          return gender_ == null ?
              com.prod.app.protobuff.Gender.GenderPb.getDefaultInstance() : gender_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.GenderPb gender = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Gender.GenderPb, com.prod.app.protobuff.Gender.GenderPb.Builder, com.prod.app.protobuff.Gender.GenderPbOrBuilder> 
          getGenderFieldBuilder() {
        if (genderBuilder_ == null) {
          genderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Gender.GenderPb, com.prod.app.protobuff.Gender.GenderPb.Builder, com.prod.app.protobuff.Gender.GenderPbOrBuilder>(
                  getGender(),
                  getParentForChildren(),
                  isClean());
          gender_ = null;
        }
        return genderBuilder_;
      }

      private com.prod.app.protobuff.Address.AddressPb address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Address.AddressPb, com.prod.app.protobuff.Address.AddressPb.Builder, com.prod.app.protobuff.Address.AddressPbOrBuilder> addressBuilder_;
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public com.prod.app.protobuff.Address.AddressPb getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.prod.app.protobuff.Address.AddressPb.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public Builder setAddress(com.prod.app.protobuff.Address.AddressPb value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public Builder setAddress(
          com.prod.app.protobuff.Address.AddressPb.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public Builder mergeAddress(com.prod.app.protobuff.Address.AddressPb value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              com.prod.app.protobuff.Address.AddressPb.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public com.prod.app.protobuff.Address.AddressPb.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      public com.prod.app.protobuff.Address.AddressPbOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.prod.app.protobuff.Address.AddressPb.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.AddressPb address = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Address.AddressPb, com.prod.app.protobuff.Address.AddressPb.Builder, com.prod.app.protobuff.Address.AddressPbOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Address.AddressPb, com.prod.app.protobuff.Address.AddressPb.Builder, com.prod.app.protobuff.Address.AddressPbOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      private com.prod.app.protobuff.Persontypeenum.PersonTypePb type_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Persontypeenum.PersonTypePb, com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder, com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder> typeBuilder_;
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public boolean hasType() {
        return typeBuilder_ != null || type_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public com.prod.app.protobuff.Persontypeenum.PersonTypePb getType() {
        if (typeBuilder_ == null) {
          return type_ == null ? com.prod.app.protobuff.Persontypeenum.PersonTypePb.getDefaultInstance() : type_;
        } else {
          return typeBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public Builder setType(com.prod.app.protobuff.Persontypeenum.PersonTypePb value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public Builder setType(
          com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder builderForValue) {
        if (typeBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public Builder mergeType(com.prod.app.protobuff.Persontypeenum.PersonTypePb value) {
        if (typeBuilder_ == null) {
          if (type_ != null) {
            type_ =
              com.prod.app.protobuff.Persontypeenum.PersonTypePb.newBuilder(type_).mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          typeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = null;
          onChanged();
        } else {
          type_ = null;
          typeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder getTypeBuilder() {
        
        onChanged();
        return getTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      public com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder getTypeOrBuilder() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilder();
        } else {
          return type_ == null ?
              com.prod.app.protobuff.Persontypeenum.PersonTypePb.getDefaultInstance() : type_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypePb type = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Persontypeenum.PersonTypePb, com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder, com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder> 
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Persontypeenum.PersonTypePb, com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder, com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder>(
                  getType(),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.ConsumerPb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.ConsumerPb)
    private static final com.prod.app.protobuff.Consumer.ConsumerPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Consumer.ConsumerPb();
    }

    public static com.prod.app.protobuff.Consumer.ConsumerPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConsumerPb>
        PARSER = new com.google.protobuf.AbstractParser<ConsumerPb>() {
      @java.lang.Override
      public ConsumerPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConsumerPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConsumerPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConsumerPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Consumer.ConsumerPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConsumerPbRefOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.ConsumerPbRef)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    boolean hasDbInfo();
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    com.prod.app.protobuff.Entity.EntityPb getDbInfo();
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    com.prod.app.protobuff.Names.NamesPb getName();
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.ConsumerPbRef}
   */
  public  static final class ConsumerPbRef extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.ConsumerPbRef)
      ConsumerPbRefOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConsumerPbRef.newBuilder() to construct.
    private ConsumerPbRef(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConsumerPbRef() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConsumerPbRef();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConsumerPbRef(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.prod.app.protobuff.Entity.EntityPb.Builder subBuilder = null;
              if (dbInfo_ != null) {
                subBuilder = dbInfo_.toBuilder();
              }
              dbInfo_ = input.readMessage(com.prod.app.protobuff.Entity.EntityPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dbInfo_);
                dbInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.prod.app.protobuff.Names.NamesPb.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(com.prod.app.protobuff.Names.NamesPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPbRef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Consumer.ConsumerPbRef.class, com.prod.app.protobuff.Consumer.ConsumerPbRef.Builder.class);
    }

    public static final int DBINFO_FIELD_NUMBER = 1;
    private com.prod.app.protobuff.Entity.EntityPb dbInfo_;
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public boolean hasDbInfo() {
      return dbInfo_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public com.prod.app.protobuff.Entity.EntityPb getDbInfo() {
      return dbInfo_ == null ? com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
    }
    /**
     * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
     */
    public com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder() {
      return getDbInfo();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.prod.app.protobuff.Names.NamesPb name_;
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public com.prod.app.protobuff.Names.NamesPb getName() {
      return name_ == null ? com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
    }
    /**
     * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
     */
    public com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder() {
      return getName();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dbInfo_ != null) {
        output.writeMessage(1, getDbInfo());
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dbInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDbInfo());
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Consumer.ConsumerPbRef)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Consumer.ConsumerPbRef other = (com.prod.app.protobuff.Consumer.ConsumerPbRef) obj;

      if (hasDbInfo() != other.hasDbInfo()) return false;
      if (hasDbInfo()) {
        if (!getDbInfo()
            .equals(other.getDbInfo())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDbInfo()) {
        hash = (37 * hash) + DBINFO_FIELD_NUMBER;
        hash = (53 * hash) + getDbInfo().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Consumer.ConsumerPbRef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Consumer.ConsumerPbRef prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.ConsumerPbRef}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.ConsumerPbRef)
        com.prod.app.protobuff.Consumer.ConsumerPbRefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPbRef_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Consumer.ConsumerPbRef.class, com.prod.app.protobuff.Consumer.ConsumerPbRef.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Consumer.ConsumerPbRef.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dbInfoBuilder_ == null) {
          dbInfo_ = null;
        } else {
          dbInfo_ = null;
          dbInfoBuilder_ = null;
        }
        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Consumer.internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPbRef getDefaultInstanceForType() {
        return com.prod.app.protobuff.Consumer.ConsumerPbRef.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPbRef build() {
        com.prod.app.protobuff.Consumer.ConsumerPbRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Consumer.ConsumerPbRef buildPartial() {
        com.prod.app.protobuff.Consumer.ConsumerPbRef result = new com.prod.app.protobuff.Consumer.ConsumerPbRef(this);
        if (dbInfoBuilder_ == null) {
          result.dbInfo_ = dbInfo_;
        } else {
          result.dbInfo_ = dbInfoBuilder_.build();
        }
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Consumer.ConsumerPbRef) {
          return mergeFrom((com.prod.app.protobuff.Consumer.ConsumerPbRef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Consumer.ConsumerPbRef other) {
        if (other == com.prod.app.protobuff.Consumer.ConsumerPbRef.getDefaultInstance()) return this;
        if (other.hasDbInfo()) {
          mergeDbInfo(other.getDbInfo());
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Consumer.ConsumerPbRef parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Consumer.ConsumerPbRef) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.prod.app.protobuff.Entity.EntityPb dbInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder> dbInfoBuilder_;
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public boolean hasDbInfo() {
        return dbInfoBuilder_ != null || dbInfo_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPb getDbInfo() {
        if (dbInfoBuilder_ == null) {
          return dbInfo_ == null ? com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
        } else {
          return dbInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder setDbInfo(com.prod.app.protobuff.Entity.EntityPb value) {
        if (dbInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dbInfo_ = value;
          onChanged();
        } else {
          dbInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder setDbInfo(
          com.prod.app.protobuff.Entity.EntityPb.Builder builderForValue) {
        if (dbInfoBuilder_ == null) {
          dbInfo_ = builderForValue.build();
          onChanged();
        } else {
          dbInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder mergeDbInfo(com.prod.app.protobuff.Entity.EntityPb value) {
        if (dbInfoBuilder_ == null) {
          if (dbInfo_ != null) {
            dbInfo_ =
              com.prod.app.protobuff.Entity.EntityPb.newBuilder(dbInfo_).mergeFrom(value).buildPartial();
          } else {
            dbInfo_ = value;
          }
          onChanged();
        } else {
          dbInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public Builder clearDbInfo() {
        if (dbInfoBuilder_ == null) {
          dbInfo_ = null;
          onChanged();
        } else {
          dbInfo_ = null;
          dbInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPb.Builder getDbInfoBuilder() {
        
        onChanged();
        return getDbInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      public com.prod.app.protobuff.Entity.EntityPbOrBuilder getDbInfoOrBuilder() {
        if (dbInfoBuilder_ != null) {
          return dbInfoBuilder_.getMessageOrBuilder();
        } else {
          return dbInfo_ == null ?
              com.prod.app.protobuff.Entity.EntityPb.getDefaultInstance() : dbInfo_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EntityPb dbInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder> 
          getDbInfoFieldBuilder() {
        if (dbInfoBuilder_ == null) {
          dbInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Entity.EntityPb, com.prod.app.protobuff.Entity.EntityPb.Builder, com.prod.app.protobuff.Entity.EntityPbOrBuilder>(
                  getDbInfo(),
                  getParentForChildren(),
                  isClean());
          dbInfo_ = null;
        }
        return dbInfoBuilder_;
      }

      private com.prod.app.protobuff.Names.NamesPb name_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder> nameBuilder_;
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPb getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder setName(com.prod.app.protobuff.Names.NamesPb value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder setName(
          com.prod.app.protobuff.Names.NamesPb.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder mergeName(com.prod.app.protobuff.Names.NamesPb value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              com.prod.app.protobuff.Names.NamesPb.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPb.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      public com.prod.app.protobuff.Names.NamesPbOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              com.prod.app.protobuff.Names.NamesPb.getDefaultInstance() : name_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.NamesPb name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Names.NamesPb, com.prod.app.protobuff.Names.NamesPb.Builder, com.prod.app.protobuff.Names.NamesPbOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.ConsumerPbRef)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.ConsumerPbRef)
    private static final com.prod.app.protobuff.Consumer.ConsumerPbRef DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Consumer.ConsumerPbRef();
    }

    public static com.prod.app.protobuff.Consumer.ConsumerPbRef getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConsumerPbRef>
        PARSER = new com.google.protobuf.AbstractParser<ConsumerPbRef>() {
      @java.lang.Override
      public ConsumerPbRef parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConsumerPbRef(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConsumerPbRef> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConsumerPbRef> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Consumer.ConsumerPbRef getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_ConsumerPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_ConsumerPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_ConsumerPbRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016consumer.proto\022\026com.prod.app.protobuff" +
      "\032\014entity.proto\032\024persontypeenum.proto\032\013na" +
      "mes.proto\032\024contactdetails.proto\032\ntime.pr" +
      "oto\032\014gender.proto\032\raddress.proto\"\366\002\n\nCon" +
      "sumerPb\0220\n\006dbInfo\030\001 \001(\0132 .com.prod.app.p" +
      "rotobuff.EntityPb\022-\n\004name\030\002 \001(\0132\037.com.pr" +
      "od.app.protobuff.NamesPb\022@\n\016contactDetai" +
      "ls\030\003 \001(\0132(.com.prod.app.protobuff.Contac" +
      "tDetailsPb\022+\n\003dob\030\004 \001(\0132\036.com.prod.app.p" +
      "rotobuff.TimePb\0220\n\006gender\030\005 \001(\0132 .com.pr" +
      "od.app.protobuff.GenderPb\0222\n\007address\030\006 \001" +
      "(\0132!.com.prod.app.protobuff.AddressPb\0222\n" +
      "\004type\030\010 \001(\0132$.com.prod.app.protobuff.Per" +
      "sonTypePb\"p\n\rConsumerPbRef\0220\n\006dbInfo\030\001 \001" +
      "(\0132 .com.prod.app.protobuff.EntityPb\022-\n\004" +
      "name\030\002 \001(\0132\037.com.prod.app.protobuff.Name" +
      "sPbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.prod.app.protobuff.Entity.getDescriptor(),
          com.prod.app.protobuff.Persontypeenum.getDescriptor(),
          com.prod.app.protobuff.Names.getDescriptor(),
          com.prod.app.protobuff.Contactdetails.getDescriptor(),
          com.prod.app.protobuff.Time.getDescriptor(),
          com.prod.app.protobuff.Gender.getDescriptor(),
          com.prod.app.protobuff.Address.getDescriptor(),
        });
    internal_static_com_prod_app_protobuff_ConsumerPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_ConsumerPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_ConsumerPb_descriptor,
        new java.lang.String[] { "DbInfo", "Name", "ContactDetails", "Dob", "Gender", "Address", "Type", });
    internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_prod_app_protobuff_ConsumerPbRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_ConsumerPbRef_descriptor,
        new java.lang.String[] { "DbInfo", "Name", });
    com.prod.app.protobuff.Entity.getDescriptor();
    com.prod.app.protobuff.Persontypeenum.getDescriptor();
    com.prod.app.protobuff.Names.getDescriptor();
    com.prod.app.protobuff.Contactdetails.getDescriptor();
    com.prod.app.protobuff.Time.getDescriptor();
    com.prod.app.protobuff.Gender.getDescriptor();
    com.prod.app.protobuff.Address.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
