// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactdetails.proto

package com.prod.app.protobuff;

public final class Contactdetails {
  private Contactdetails() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactDetailsPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.ContactDetailsPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    boolean hasEmail();
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPb getEmail();
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPbOrBuilder getEmailOrBuilder();

    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    boolean hasPrimaryMobile();
    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    com.prod.app.protobuff.Mobile.MobilePb getPrimaryMobile();
    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    com.prod.app.protobuff.Mobile.MobilePbOrBuilder getPrimaryMobileOrBuilder();

    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    java.util.List<com.prod.app.protobuff.Mobile.MobilePb> 
        getSecondryMobileList();
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    com.prod.app.protobuff.Mobile.MobilePb getSecondryMobile(int index);
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    int getSecondryMobileCount();
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    java.util.List<? extends com.prod.app.protobuff.Mobile.MobilePbOrBuilder> 
        getSecondryMobileOrBuilderList();
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    com.prod.app.protobuff.Mobile.MobilePbOrBuilder getSecondryMobileOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.ContactDetailsPb}
   */
  public  static final class ContactDetailsPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.ContactDetailsPb)
      ContactDetailsPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactDetailsPb.newBuilder() to construct.
    private ContactDetailsPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactDetailsPb() {
      secondryMobile_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactDetailsPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactDetailsPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.prod.app.protobuff.Email.EmailIdPb.Builder subBuilder = null;
              if (email_ != null) {
                subBuilder = email_.toBuilder();
              }
              email_ = input.readMessage(com.prod.app.protobuff.Email.EmailIdPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(email_);
                email_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.prod.app.protobuff.Mobile.MobilePb.Builder subBuilder = null;
              if (primaryMobile_ != null) {
                subBuilder = primaryMobile_.toBuilder();
              }
              primaryMobile_ = input.readMessage(com.prod.app.protobuff.Mobile.MobilePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(primaryMobile_);
                primaryMobile_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                secondryMobile_ = new java.util.ArrayList<com.prod.app.protobuff.Mobile.MobilePb>();
                mutable_bitField0_ |= 0x00000001;
              }
              secondryMobile_.add(
                  input.readMessage(com.prod.app.protobuff.Mobile.MobilePb.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          secondryMobile_ = java.util.Collections.unmodifiableList(secondryMobile_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Contactdetails.internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Contactdetails.internal_static_com_prod_app_protobuff_ContactDetailsPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Contactdetails.ContactDetailsPb.class, com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder.class);
    }

    public static final int EMAIL_FIELD_NUMBER = 1;
    private com.prod.app.protobuff.Email.EmailIdPb email_;
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    public boolean hasEmail() {
      return email_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPb getEmail() {
      return email_ == null ? com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : email_;
    }
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getEmailOrBuilder() {
      return getEmail();
    }

    public static final int PRIMARYMOBILE_FIELD_NUMBER = 2;
    private com.prod.app.protobuff.Mobile.MobilePb primaryMobile_;
    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    public boolean hasPrimaryMobile() {
      return primaryMobile_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    public com.prod.app.protobuff.Mobile.MobilePb getPrimaryMobile() {
      return primaryMobile_ == null ? com.prod.app.protobuff.Mobile.MobilePb.getDefaultInstance() : primaryMobile_;
    }
    /**
     * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
     */
    public com.prod.app.protobuff.Mobile.MobilePbOrBuilder getPrimaryMobileOrBuilder() {
      return getPrimaryMobile();
    }

    public static final int SECONDRYMOBILE_FIELD_NUMBER = 3;
    private java.util.List<com.prod.app.protobuff.Mobile.MobilePb> secondryMobile_;
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    public java.util.List<com.prod.app.protobuff.Mobile.MobilePb> getSecondryMobileList() {
      return secondryMobile_;
    }
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    public java.util.List<? extends com.prod.app.protobuff.Mobile.MobilePbOrBuilder> 
        getSecondryMobileOrBuilderList() {
      return secondryMobile_;
    }
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    public int getSecondryMobileCount() {
      return secondryMobile_.size();
    }
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    public com.prod.app.protobuff.Mobile.MobilePb getSecondryMobile(int index) {
      return secondryMobile_.get(index);
    }
    /**
     * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
     */
    public com.prod.app.protobuff.Mobile.MobilePbOrBuilder getSecondryMobileOrBuilder(
        int index) {
      return secondryMobile_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (email_ != null) {
        output.writeMessage(1, getEmail());
      }
      if (primaryMobile_ != null) {
        output.writeMessage(2, getPrimaryMobile());
      }
      for (int i = 0; i < secondryMobile_.size(); i++) {
        output.writeMessage(3, secondryMobile_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (email_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEmail());
      }
      if (primaryMobile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPrimaryMobile());
      }
      for (int i = 0; i < secondryMobile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, secondryMobile_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Contactdetails.ContactDetailsPb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Contactdetails.ContactDetailsPb other = (com.prod.app.protobuff.Contactdetails.ContactDetailsPb) obj;

      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasPrimaryMobile() != other.hasPrimaryMobile()) return false;
      if (hasPrimaryMobile()) {
        if (!getPrimaryMobile()
            .equals(other.getPrimaryMobile())) return false;
      }
      if (!getSecondryMobileList()
          .equals(other.getSecondryMobileList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasPrimaryMobile()) {
        hash = (37 * hash) + PRIMARYMOBILE_FIELD_NUMBER;
        hash = (53 * hash) + getPrimaryMobile().hashCode();
      }
      if (getSecondryMobileCount() > 0) {
        hash = (37 * hash) + SECONDRYMOBILE_FIELD_NUMBER;
        hash = (53 * hash) + getSecondryMobileList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Contactdetails.ContactDetailsPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.ContactDetailsPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.ContactDetailsPb)
        com.prod.app.protobuff.Contactdetails.ContactDetailsPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Contactdetails.internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Contactdetails.internal_static_com_prod_app_protobuff_ContactDetailsPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Contactdetails.ContactDetailsPb.class, com.prod.app.protobuff.Contactdetails.ContactDetailsPb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Contactdetails.ContactDetailsPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecondryMobileFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (emailBuilder_ == null) {
          email_ = null;
        } else {
          email_ = null;
          emailBuilder_ = null;
        }
        if (primaryMobileBuilder_ == null) {
          primaryMobile_ = null;
        } else {
          primaryMobile_ = null;
          primaryMobileBuilder_ = null;
        }
        if (secondryMobileBuilder_ == null) {
          secondryMobile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          secondryMobileBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Contactdetails.internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Contactdetails.ContactDetailsPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPb build() {
        com.prod.app.protobuff.Contactdetails.ContactDetailsPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Contactdetails.ContactDetailsPb buildPartial() {
        com.prod.app.protobuff.Contactdetails.ContactDetailsPb result = new com.prod.app.protobuff.Contactdetails.ContactDetailsPb(this);
        int from_bitField0_ = bitField0_;
        if (emailBuilder_ == null) {
          result.email_ = email_;
        } else {
          result.email_ = emailBuilder_.build();
        }
        if (primaryMobileBuilder_ == null) {
          result.primaryMobile_ = primaryMobile_;
        } else {
          result.primaryMobile_ = primaryMobileBuilder_.build();
        }
        if (secondryMobileBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            secondryMobile_ = java.util.Collections.unmodifiableList(secondryMobile_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.secondryMobile_ = secondryMobile_;
        } else {
          result.secondryMobile_ = secondryMobileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Contactdetails.ContactDetailsPb) {
          return mergeFrom((com.prod.app.protobuff.Contactdetails.ContactDetailsPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Contactdetails.ContactDetailsPb other) {
        if (other == com.prod.app.protobuff.Contactdetails.ContactDetailsPb.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          mergeEmail(other.getEmail());
        }
        if (other.hasPrimaryMobile()) {
          mergePrimaryMobile(other.getPrimaryMobile());
        }
        if (secondryMobileBuilder_ == null) {
          if (!other.secondryMobile_.isEmpty()) {
            if (secondryMobile_.isEmpty()) {
              secondryMobile_ = other.secondryMobile_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSecondryMobileIsMutable();
              secondryMobile_.addAll(other.secondryMobile_);
            }
            onChanged();
          }
        } else {
          if (!other.secondryMobile_.isEmpty()) {
            if (secondryMobileBuilder_.isEmpty()) {
              secondryMobileBuilder_.dispose();
              secondryMobileBuilder_ = null;
              secondryMobile_ = other.secondryMobile_;
              bitField0_ = (bitField0_ & ~0x00000001);
              secondryMobileBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSecondryMobileFieldBuilder() : null;
            } else {
              secondryMobileBuilder_.addAllMessages(other.secondryMobile_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Contactdetails.ContactDetailsPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Contactdetails.ContactDetailsPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.prod.app.protobuff.Email.EmailIdPb email_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> emailBuilder_;
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public boolean hasEmail() {
        return emailBuilder_ != null || email_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb getEmail() {
        if (emailBuilder_ == null) {
          return email_ == null ? com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : email_;
        } else {
          return emailBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public Builder setEmail(com.prod.app.protobuff.Email.EmailIdPb value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          email_ = value;
          onChanged();
        } else {
          emailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public Builder setEmail(
          com.prod.app.protobuff.Email.EmailIdPb.Builder builderForValue) {
        if (emailBuilder_ == null) {
          email_ = builderForValue.build();
          onChanged();
        } else {
          emailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public Builder mergeEmail(com.prod.app.protobuff.Email.EmailIdPb value) {
        if (emailBuilder_ == null) {
          if (email_ != null) {
            email_ =
              com.prod.app.protobuff.Email.EmailIdPb.newBuilder(email_).mergeFrom(value).buildPartial();
          } else {
            email_ = value;
          }
          onChanged();
        } else {
          emailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public Builder clearEmail() {
        if (emailBuilder_ == null) {
          email_ = null;
          onChanged();
        } else {
          email_ = null;
          emailBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb.Builder getEmailBuilder() {
        
        onChanged();
        return getEmailFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getEmailOrBuilder() {
        if (emailBuilder_ != null) {
          return emailBuilder_.getMessageOrBuilder();
        } else {
          return email_ == null ?
              com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : email_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb email = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
          getEmailFieldBuilder() {
        if (emailBuilder_ == null) {
          emailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder>(
                  getEmail(),
                  getParentForChildren(),
                  isClean());
          email_ = null;
        }
        return emailBuilder_;
      }

      private com.prod.app.protobuff.Mobile.MobilePb primaryMobile_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder> primaryMobileBuilder_;
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public boolean hasPrimaryMobile() {
        return primaryMobileBuilder_ != null || primaryMobile_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb getPrimaryMobile() {
        if (primaryMobileBuilder_ == null) {
          return primaryMobile_ == null ? com.prod.app.protobuff.Mobile.MobilePb.getDefaultInstance() : primaryMobile_;
        } else {
          return primaryMobileBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public Builder setPrimaryMobile(com.prod.app.protobuff.Mobile.MobilePb value) {
        if (primaryMobileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          primaryMobile_ = value;
          onChanged();
        } else {
          primaryMobileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public Builder setPrimaryMobile(
          com.prod.app.protobuff.Mobile.MobilePb.Builder builderForValue) {
        if (primaryMobileBuilder_ == null) {
          primaryMobile_ = builderForValue.build();
          onChanged();
        } else {
          primaryMobileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public Builder mergePrimaryMobile(com.prod.app.protobuff.Mobile.MobilePb value) {
        if (primaryMobileBuilder_ == null) {
          if (primaryMobile_ != null) {
            primaryMobile_ =
              com.prod.app.protobuff.Mobile.MobilePb.newBuilder(primaryMobile_).mergeFrom(value).buildPartial();
          } else {
            primaryMobile_ = value;
          }
          onChanged();
        } else {
          primaryMobileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public Builder clearPrimaryMobile() {
        if (primaryMobileBuilder_ == null) {
          primaryMobile_ = null;
          onChanged();
        } else {
          primaryMobile_ = null;
          primaryMobileBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb.Builder getPrimaryMobileBuilder() {
        
        onChanged();
        return getPrimaryMobileFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePbOrBuilder getPrimaryMobileOrBuilder() {
        if (primaryMobileBuilder_ != null) {
          return primaryMobileBuilder_.getMessageOrBuilder();
        } else {
          return primaryMobile_ == null ?
              com.prod.app.protobuff.Mobile.MobilePb.getDefaultInstance() : primaryMobile_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.MobilePb primaryMobile = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder> 
          getPrimaryMobileFieldBuilder() {
        if (primaryMobileBuilder_ == null) {
          primaryMobileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder>(
                  getPrimaryMobile(),
                  getParentForChildren(),
                  isClean());
          primaryMobile_ = null;
        }
        return primaryMobileBuilder_;
      }

      private java.util.List<com.prod.app.protobuff.Mobile.MobilePb> secondryMobile_ =
        java.util.Collections.emptyList();
      private void ensureSecondryMobileIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          secondryMobile_ = new java.util.ArrayList<com.prod.app.protobuff.Mobile.MobilePb>(secondryMobile_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder> secondryMobileBuilder_;

      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public java.util.List<com.prod.app.protobuff.Mobile.MobilePb> getSecondryMobileList() {
        if (secondryMobileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(secondryMobile_);
        } else {
          return secondryMobileBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public int getSecondryMobileCount() {
        if (secondryMobileBuilder_ == null) {
          return secondryMobile_.size();
        } else {
          return secondryMobileBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb getSecondryMobile(int index) {
        if (secondryMobileBuilder_ == null) {
          return secondryMobile_.get(index);
        } else {
          return secondryMobileBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder setSecondryMobile(
          int index, com.prod.app.protobuff.Mobile.MobilePb value) {
        if (secondryMobileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondryMobileIsMutable();
          secondryMobile_.set(index, value);
          onChanged();
        } else {
          secondryMobileBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder setSecondryMobile(
          int index, com.prod.app.protobuff.Mobile.MobilePb.Builder builderForValue) {
        if (secondryMobileBuilder_ == null) {
          ensureSecondryMobileIsMutable();
          secondryMobile_.set(index, builderForValue.build());
          onChanged();
        } else {
          secondryMobileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder addSecondryMobile(com.prod.app.protobuff.Mobile.MobilePb value) {
        if (secondryMobileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondryMobileIsMutable();
          secondryMobile_.add(value);
          onChanged();
        } else {
          secondryMobileBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder addSecondryMobile(
          int index, com.prod.app.protobuff.Mobile.MobilePb value) {
        if (secondryMobileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondryMobileIsMutable();
          secondryMobile_.add(index, value);
          onChanged();
        } else {
          secondryMobileBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder addSecondryMobile(
          com.prod.app.protobuff.Mobile.MobilePb.Builder builderForValue) {
        if (secondryMobileBuilder_ == null) {
          ensureSecondryMobileIsMutable();
          secondryMobile_.add(builderForValue.build());
          onChanged();
        } else {
          secondryMobileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder addSecondryMobile(
          int index, com.prod.app.protobuff.Mobile.MobilePb.Builder builderForValue) {
        if (secondryMobileBuilder_ == null) {
          ensureSecondryMobileIsMutable();
          secondryMobile_.add(index, builderForValue.build());
          onChanged();
        } else {
          secondryMobileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder addAllSecondryMobile(
          java.lang.Iterable<? extends com.prod.app.protobuff.Mobile.MobilePb> values) {
        if (secondryMobileBuilder_ == null) {
          ensureSecondryMobileIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, secondryMobile_);
          onChanged();
        } else {
          secondryMobileBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder clearSecondryMobile() {
        if (secondryMobileBuilder_ == null) {
          secondryMobile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          secondryMobileBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public Builder removeSecondryMobile(int index) {
        if (secondryMobileBuilder_ == null) {
          ensureSecondryMobileIsMutable();
          secondryMobile_.remove(index);
          onChanged();
        } else {
          secondryMobileBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb.Builder getSecondryMobileBuilder(
          int index) {
        return getSecondryMobileFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePbOrBuilder getSecondryMobileOrBuilder(
          int index) {
        if (secondryMobileBuilder_ == null) {
          return secondryMobile_.get(index);  } else {
          return secondryMobileBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public java.util.List<? extends com.prod.app.protobuff.Mobile.MobilePbOrBuilder> 
           getSecondryMobileOrBuilderList() {
        if (secondryMobileBuilder_ != null) {
          return secondryMobileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(secondryMobile_);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb.Builder addSecondryMobileBuilder() {
        return getSecondryMobileFieldBuilder().addBuilder(
            com.prod.app.protobuff.Mobile.MobilePb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public com.prod.app.protobuff.Mobile.MobilePb.Builder addSecondryMobileBuilder(
          int index) {
        return getSecondryMobileFieldBuilder().addBuilder(
            index, com.prod.app.protobuff.Mobile.MobilePb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.prod.app.protobuff.MobilePb secondryMobile = 3;</code>
       */
      public java.util.List<com.prod.app.protobuff.Mobile.MobilePb.Builder> 
           getSecondryMobileBuilderList() {
        return getSecondryMobileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder> 
          getSecondryMobileFieldBuilder() {
        if (secondryMobileBuilder_ == null) {
          secondryMobileBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.prod.app.protobuff.Mobile.MobilePb, com.prod.app.protobuff.Mobile.MobilePb.Builder, com.prod.app.protobuff.Mobile.MobilePbOrBuilder>(
                  secondryMobile_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          secondryMobile_ = null;
        }
        return secondryMobileBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.ContactDetailsPb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.ContactDetailsPb)
    private static final com.prod.app.protobuff.Contactdetails.ContactDetailsPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Contactdetails.ContactDetailsPb();
    }

    public static com.prod.app.protobuff.Contactdetails.ContactDetailsPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactDetailsPb>
        PARSER = new com.google.protobuf.AbstractParser<ContactDetailsPb>() {
      @java.lang.Override
      public ContactDetailsPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactDetailsPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactDetailsPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactDetailsPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Contactdetails.ContactDetailsPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_ContactDetailsPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024contactdetails.proto\022\026com.prod.app.pro" +
      "tobuff\032\013email.proto\032\014mobile.proto\"\267\001\n\020Co" +
      "ntactDetailsPb\0220\n\005email\030\001 \001(\0132!.com.prod" +
      ".app.protobuff.EmailIdPb\0227\n\rprimaryMobil" +
      "e\030\002 \001(\0132 .com.prod.app.protobuff.MobileP" +
      "b\0228\n\016secondryMobile\030\003 \003(\0132 .com.prod.app" +
      ".protobuff.MobilePbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.prod.app.protobuff.Email.getDescriptor(),
          com.prod.app.protobuff.Mobile.getDescriptor(),
        });
    internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_ContactDetailsPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_ContactDetailsPb_descriptor,
        new java.lang.String[] { "Email", "PrimaryMobile", "SecondryMobile", });
    com.prod.app.protobuff.Email.getDescriptor();
    com.prod.app.protobuff.Mobile.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
