// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: email.proto

package com.prod.app.protobuff;

public final class Email {
  private Email() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmailIdPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.EmailIdPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string localPart = 1;</code>
     */
    java.lang.String getLocalPart();
    /**
     * <code>string localPart = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocalPartBytes();

    /**
     * <code>string domain = 2;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 2;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.EmailIdPb}
   */
  public  static final class EmailIdPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.EmailIdPb)
      EmailIdPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmailIdPb.newBuilder() to construct.
    private EmailIdPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmailIdPb() {
      localPart_ = "";
      domain_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmailIdPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmailIdPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              localPart_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailIdPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailIdPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Email.EmailIdPb.class, com.prod.app.protobuff.Email.EmailIdPb.Builder.class);
    }

    public static final int LOCALPART_FIELD_NUMBER = 1;
    private volatile java.lang.Object localPart_;
    /**
     * <code>string localPart = 1;</code>
     */
    public java.lang.String getLocalPart() {
      java.lang.Object ref = localPart_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localPart_ = s;
        return s;
      }
    }
    /**
     * <code>string localPart = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocalPartBytes() {
      java.lang.Object ref = localPart_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object domain_;
    /**
     * <code>string domain = 2;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>string domain = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocalPartBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, localPart_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domain_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocalPartBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, localPart_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domain_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Email.EmailIdPb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Email.EmailIdPb other = (com.prod.app.protobuff.Email.EmailIdPb) obj;

      if (!getLocalPart()
          .equals(other.getLocalPart())) return false;
      if (!getDomain()
          .equals(other.getDomain())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCALPART_FIELD_NUMBER;
      hash = (53 * hash) + getLocalPart().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailIdPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Email.EmailIdPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.EmailIdPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.EmailIdPb)
        com.prod.app.protobuff.Email.EmailIdPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailIdPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailIdPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Email.EmailIdPb.class, com.prod.app.protobuff.Email.EmailIdPb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Email.EmailIdPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        localPart_ = "";

        domain_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailIdPb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailIdPb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailIdPb build() {
        com.prod.app.protobuff.Email.EmailIdPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailIdPb buildPartial() {
        com.prod.app.protobuff.Email.EmailIdPb result = new com.prod.app.protobuff.Email.EmailIdPb(this);
        result.localPart_ = localPart_;
        result.domain_ = domain_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Email.EmailIdPb) {
          return mergeFrom((com.prod.app.protobuff.Email.EmailIdPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Email.EmailIdPb other) {
        if (other == com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance()) return this;
        if (!other.getLocalPart().isEmpty()) {
          localPart_ = other.localPart_;
          onChanged();
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Email.EmailIdPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Email.EmailIdPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object localPart_ = "";
      /**
       * <code>string localPart = 1;</code>
       */
      public java.lang.String getLocalPart() {
        java.lang.Object ref = localPart_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localPart_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localPart = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocalPartBytes() {
        java.lang.Object ref = localPart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localPart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localPart = 1;</code>
       */
      public Builder setLocalPart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localPart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localPart = 1;</code>
       */
      public Builder clearLocalPart() {
        
        localPart_ = getDefaultInstance().getLocalPart();
        onChanged();
        return this;
      }
      /**
       * <code>string localPart = 1;</code>
       */
      public Builder setLocalPartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localPart_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>string domain = 2;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain = 2;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 2;</code>
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 2;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.EmailIdPb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.EmailIdPb)
    private static final com.prod.app.protobuff.Email.EmailIdPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Email.EmailIdPb();
    }

    public static com.prod.app.protobuff.Email.EmailIdPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmailIdPb>
        PARSER = new com.google.protobuf.AbstractParser<EmailIdPb>() {
      @java.lang.Override
      public EmailIdPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmailIdPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmailIdPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmailIdPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Email.EmailIdPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmailBuilderPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.EmailBuilderPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    boolean hasFromId();
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPb getFromId();
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPbOrBuilder getFromIdOrBuilder();

    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    java.util.List<com.prod.app.protobuff.Email.EmailIdPb> 
        getToIdList();
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPb getToId(int index);
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    int getToIdCount();
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    java.util.List<? extends com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
        getToIdOrBuilderList();
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    com.prod.app.protobuff.Email.EmailIdPbOrBuilder getToIdOrBuilder(
        int index);

    /**
     * <code>string subject = 3;</code>
     */
    java.lang.String getSubject();
    /**
     * <code>string subject = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <code>string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.EmailBuilderPb}
   */
  public  static final class EmailBuilderPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.EmailBuilderPb)
      EmailBuilderPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmailBuilderPb.newBuilder() to construct.
    private EmailBuilderPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmailBuilderPb() {
      toId_ = java.util.Collections.emptyList();
      subject_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmailBuilderPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmailBuilderPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.prod.app.protobuff.Email.EmailIdPb.Builder subBuilder = null;
              if (fromId_ != null) {
                subBuilder = fromId_.toBuilder();
              }
              fromId_ = input.readMessage(com.prod.app.protobuff.Email.EmailIdPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fromId_);
                fromId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                toId_ = new java.util.ArrayList<com.prod.app.protobuff.Email.EmailIdPb>();
                mutable_bitField0_ |= 0x00000001;
              }
              toId_.add(
                  input.readMessage(com.prod.app.protobuff.Email.EmailIdPb.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          toId_ = java.util.Collections.unmodifiableList(toId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailBuilderPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Email.EmailBuilderPb.class, com.prod.app.protobuff.Email.EmailBuilderPb.Builder.class);
    }

    public static final int FROMID_FIELD_NUMBER = 1;
    private com.prod.app.protobuff.Email.EmailIdPb fromId_;
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    public boolean hasFromId() {
      return fromId_ != null;
    }
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPb getFromId() {
      return fromId_ == null ? com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : fromId_;
    }
    /**
     * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getFromIdOrBuilder() {
      return getFromId();
    }

    public static final int TOID_FIELD_NUMBER = 2;
    private java.util.List<com.prod.app.protobuff.Email.EmailIdPb> toId_;
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    public java.util.List<com.prod.app.protobuff.Email.EmailIdPb> getToIdList() {
      return toId_;
    }
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    public java.util.List<? extends com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
        getToIdOrBuilderList() {
      return toId_;
    }
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    public int getToIdCount() {
      return toId_.size();
    }
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPb getToId(int index) {
      return toId_.get(index);
    }
    /**
     * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
     */
    public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getToIdOrBuilder(
        int index) {
      return toId_.get(index);
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object subject_;
    /**
     * <code>string subject = 3;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <code>string subject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromId_ != null) {
        output.writeMessage(1, getFromId());
      }
      for (int i = 0; i < toId_.size(); i++) {
        output.writeMessage(2, toId_.get(i));
      }
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subject_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFromId());
      }
      for (int i = 0; i < toId_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, toId_.get(i));
      }
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subject_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Email.EmailBuilderPb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Email.EmailBuilderPb other = (com.prod.app.protobuff.Email.EmailBuilderPb) obj;

      if (hasFromId() != other.hasFromId()) return false;
      if (hasFromId()) {
        if (!getFromId()
            .equals(other.getFromId())) return false;
      }
      if (!getToIdList()
          .equals(other.getToIdList())) return false;
      if (!getSubject()
          .equals(other.getSubject())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + getFromId().hashCode();
      }
      if (getToIdCount() > 0) {
        hash = (37 * hash) + TOID_FIELD_NUMBER;
        hash = (53 * hash) + getToIdList().hashCode();
      }
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Email.EmailBuilderPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Email.EmailBuilderPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.EmailBuilderPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.EmailBuilderPb)
        com.prod.app.protobuff.Email.EmailBuilderPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailBuilderPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Email.EmailBuilderPb.class, com.prod.app.protobuff.Email.EmailBuilderPb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Email.EmailBuilderPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getToIdFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fromIdBuilder_ == null) {
          fromId_ = null;
        } else {
          fromId_ = null;
          fromIdBuilder_ = null;
        }
        if (toIdBuilder_ == null) {
          toId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          toIdBuilder_.clear();
        }
        subject_ = "";

        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Email.internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailBuilderPb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Email.EmailBuilderPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailBuilderPb build() {
        com.prod.app.protobuff.Email.EmailBuilderPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Email.EmailBuilderPb buildPartial() {
        com.prod.app.protobuff.Email.EmailBuilderPb result = new com.prod.app.protobuff.Email.EmailBuilderPb(this);
        int from_bitField0_ = bitField0_;
        if (fromIdBuilder_ == null) {
          result.fromId_ = fromId_;
        } else {
          result.fromId_ = fromIdBuilder_.build();
        }
        if (toIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            toId_ = java.util.Collections.unmodifiableList(toId_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.toId_ = toId_;
        } else {
          result.toId_ = toIdBuilder_.build();
        }
        result.subject_ = subject_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Email.EmailBuilderPb) {
          return mergeFrom((com.prod.app.protobuff.Email.EmailBuilderPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Email.EmailBuilderPb other) {
        if (other == com.prod.app.protobuff.Email.EmailBuilderPb.getDefaultInstance()) return this;
        if (other.hasFromId()) {
          mergeFromId(other.getFromId());
        }
        if (toIdBuilder_ == null) {
          if (!other.toId_.isEmpty()) {
            if (toId_.isEmpty()) {
              toId_ = other.toId_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureToIdIsMutable();
              toId_.addAll(other.toId_);
            }
            onChanged();
          }
        } else {
          if (!other.toId_.isEmpty()) {
            if (toIdBuilder_.isEmpty()) {
              toIdBuilder_.dispose();
              toIdBuilder_ = null;
              toId_ = other.toId_;
              bitField0_ = (bitField0_ & ~0x00000001);
              toIdBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getToIdFieldBuilder() : null;
            } else {
              toIdBuilder_.addAllMessages(other.toId_);
            }
          }
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Email.EmailBuilderPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Email.EmailBuilderPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.prod.app.protobuff.Email.EmailIdPb fromId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> fromIdBuilder_;
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public boolean hasFromId() {
        return fromIdBuilder_ != null || fromId_ != null;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb getFromId() {
        if (fromIdBuilder_ == null) {
          return fromId_ == null ? com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : fromId_;
        } else {
          return fromIdBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public Builder setFromId(com.prod.app.protobuff.Email.EmailIdPb value) {
        if (fromIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromId_ = value;
          onChanged();
        } else {
          fromIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public Builder setFromId(
          com.prod.app.protobuff.Email.EmailIdPb.Builder builderForValue) {
        if (fromIdBuilder_ == null) {
          fromId_ = builderForValue.build();
          onChanged();
        } else {
          fromIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public Builder mergeFromId(com.prod.app.protobuff.Email.EmailIdPb value) {
        if (fromIdBuilder_ == null) {
          if (fromId_ != null) {
            fromId_ =
              com.prod.app.protobuff.Email.EmailIdPb.newBuilder(fromId_).mergeFrom(value).buildPartial();
          } else {
            fromId_ = value;
          }
          onChanged();
        } else {
          fromIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public Builder clearFromId() {
        if (fromIdBuilder_ == null) {
          fromId_ = null;
          onChanged();
        } else {
          fromId_ = null;
          fromIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb.Builder getFromIdBuilder() {
        
        onChanged();
        return getFromIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getFromIdOrBuilder() {
        if (fromIdBuilder_ != null) {
          return fromIdBuilder_.getMessageOrBuilder();
        } else {
          return fromId_ == null ?
              com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance() : fromId_;
        }
      }
      /**
       * <code>.com.prod.app.protobuff.EmailIdPb fromId = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
          getFromIdFieldBuilder() {
        if (fromIdBuilder_ == null) {
          fromIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder>(
                  getFromId(),
                  getParentForChildren(),
                  isClean());
          fromId_ = null;
        }
        return fromIdBuilder_;
      }

      private java.util.List<com.prod.app.protobuff.Email.EmailIdPb> toId_ =
        java.util.Collections.emptyList();
      private void ensureToIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          toId_ = new java.util.ArrayList<com.prod.app.protobuff.Email.EmailIdPb>(toId_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> toIdBuilder_;

      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public java.util.List<com.prod.app.protobuff.Email.EmailIdPb> getToIdList() {
        if (toIdBuilder_ == null) {
          return java.util.Collections.unmodifiableList(toId_);
        } else {
          return toIdBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public int getToIdCount() {
        if (toIdBuilder_ == null) {
          return toId_.size();
        } else {
          return toIdBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb getToId(int index) {
        if (toIdBuilder_ == null) {
          return toId_.get(index);
        } else {
          return toIdBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder setToId(
          int index, com.prod.app.protobuff.Email.EmailIdPb value) {
        if (toIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIdIsMutable();
          toId_.set(index, value);
          onChanged();
        } else {
          toIdBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder setToId(
          int index, com.prod.app.protobuff.Email.EmailIdPb.Builder builderForValue) {
        if (toIdBuilder_ == null) {
          ensureToIdIsMutable();
          toId_.set(index, builderForValue.build());
          onChanged();
        } else {
          toIdBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder addToId(com.prod.app.protobuff.Email.EmailIdPb value) {
        if (toIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIdIsMutable();
          toId_.add(value);
          onChanged();
        } else {
          toIdBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder addToId(
          int index, com.prod.app.protobuff.Email.EmailIdPb value) {
        if (toIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToIdIsMutable();
          toId_.add(index, value);
          onChanged();
        } else {
          toIdBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder addToId(
          com.prod.app.protobuff.Email.EmailIdPb.Builder builderForValue) {
        if (toIdBuilder_ == null) {
          ensureToIdIsMutable();
          toId_.add(builderForValue.build());
          onChanged();
        } else {
          toIdBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder addToId(
          int index, com.prod.app.protobuff.Email.EmailIdPb.Builder builderForValue) {
        if (toIdBuilder_ == null) {
          ensureToIdIsMutable();
          toId_.add(index, builderForValue.build());
          onChanged();
        } else {
          toIdBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder addAllToId(
          java.lang.Iterable<? extends com.prod.app.protobuff.Email.EmailIdPb> values) {
        if (toIdBuilder_ == null) {
          ensureToIdIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, toId_);
          onChanged();
        } else {
          toIdBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder clearToId() {
        if (toIdBuilder_ == null) {
          toId_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          toIdBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public Builder removeToId(int index) {
        if (toIdBuilder_ == null) {
          ensureToIdIsMutable();
          toId_.remove(index);
          onChanged();
        } else {
          toIdBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb.Builder getToIdBuilder(
          int index) {
        return getToIdFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPbOrBuilder getToIdOrBuilder(
          int index) {
        if (toIdBuilder_ == null) {
          return toId_.get(index);  } else {
          return toIdBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public java.util.List<? extends com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
           getToIdOrBuilderList() {
        if (toIdBuilder_ != null) {
          return toIdBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(toId_);
        }
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb.Builder addToIdBuilder() {
        return getToIdFieldBuilder().addBuilder(
            com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public com.prod.app.protobuff.Email.EmailIdPb.Builder addToIdBuilder(
          int index) {
        return getToIdFieldBuilder().addBuilder(
            index, com.prod.app.protobuff.Email.EmailIdPb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.prod.app.protobuff.EmailIdPb toId = 2;</code>
       */
      public java.util.List<com.prod.app.protobuff.Email.EmailIdPb.Builder> 
           getToIdBuilderList() {
        return getToIdFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder> 
          getToIdFieldBuilder() {
        if (toIdBuilder_ == null) {
          toIdBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.prod.app.protobuff.Email.EmailIdPb, com.prod.app.protobuff.Email.EmailIdPb.Builder, com.prod.app.protobuff.Email.EmailIdPbOrBuilder>(
                  toId_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          toId_ = null;
        }
        return toIdBuilder_;
      }

      private java.lang.Object subject_ = "";
      /**
       * <code>string subject = 3;</code>
       */
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder setSubject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <code>string subject = 3;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.EmailBuilderPb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.EmailBuilderPb)
    private static final com.prod.app.protobuff.Email.EmailBuilderPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Email.EmailBuilderPb();
    }

    public static com.prod.app.protobuff.Email.EmailBuilderPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmailBuilderPb>
        PARSER = new com.google.protobuf.AbstractParser<EmailBuilderPb>() {
      @java.lang.Override
      public EmailBuilderPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmailBuilderPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmailBuilderPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmailBuilderPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Email.EmailBuilderPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_EmailIdPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_EmailIdPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_EmailBuilderPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013email.proto\022\026com.prod.app.protobuff\".\n" +
      "\tEmailIdPb\022\021\n\tlocalPart\030\001 \001(\t\022\016\n\006domain\030" +
      "\002 \001(\t\"\226\001\n\016EmailBuilderPb\0221\n\006fromId\030\001 \001(\013" +
      "2!.com.prod.app.protobuff.EmailIdPb\022/\n\004t" +
      "oId\030\002 \003(\0132!.com.prod.app.protobuff.Email" +
      "IdPb\022\017\n\007subject\030\003 \001(\t\022\017\n\007content\030\004 \001(\tb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_prod_app_protobuff_EmailIdPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_EmailIdPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_EmailIdPb_descriptor,
        new java.lang.String[] { "LocalPart", "Domain", });
    internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_prod_app_protobuff_EmailBuilderPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_EmailBuilderPb_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Subject", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
