// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: persontypeenum.proto

package com.prod.app.protobuff;

public final class Persontypeenum {
  private Persontypeenum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.prod.app.protobuff.PersonTypeEnum}
   */
  public enum PersonTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_PERSON_TYPE = 0;</code>
     */
    UNKNOWN_PERSON_TYPE(0),
    /**
     * <code>WORKER = 1;</code>
     */
    WORKER(1),
    /**
     * <code>CONSUMER = 2;</code>
     */
    CONSUMER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_PERSON_TYPE = 0;</code>
     */
    public static final int UNKNOWN_PERSON_TYPE_VALUE = 0;
    /**
     * <code>WORKER = 1;</code>
     */
    public static final int WORKER_VALUE = 1;
    /**
     * <code>CONSUMER = 2;</code>
     */
    public static final int CONSUMER_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PersonTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    public static PersonTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_PERSON_TYPE;
        case 1: return WORKER;
        case 2: return CONSUMER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PersonTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PersonTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PersonTypeEnum>() {
            public PersonTypeEnum findValueByNumber(int number) {
              return PersonTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.prod.app.protobuff.Persontypeenum.getDescriptor().getEnumTypes().get(0);
    }

    private static final PersonTypeEnum[] VALUES = values();

    public static PersonTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PersonTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.prod.app.protobuff.PersonTypeEnum)
  }

  public interface PersonTypePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.PersonTypePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
     */
    int getPersonTypeValue();
    /**
     * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
     */
    com.prod.app.protobuff.Persontypeenum.PersonTypeEnum getPersonType();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.PersonTypePb}
   */
  public  static final class PersonTypePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.PersonTypePb)
      PersonTypePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonTypePb.newBuilder() to construct.
    private PersonTypePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonTypePb() {
      personType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PersonTypePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonTypePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              personType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Persontypeenum.internal_static_com_prod_app_protobuff_PersonTypePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Persontypeenum.internal_static_com_prod_app_protobuff_PersonTypePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Persontypeenum.PersonTypePb.class, com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder.class);
    }

    public static final int PERSONTYPE_FIELD_NUMBER = 1;
    private int personType_;
    /**
     * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
     */
    public int getPersonTypeValue() {
      return personType_;
    }
    /**
     * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
     */
    public com.prod.app.protobuff.Persontypeenum.PersonTypeEnum getPersonType() {
      @SuppressWarnings("deprecation")
      com.prod.app.protobuff.Persontypeenum.PersonTypeEnum result = com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.valueOf(personType_);
      return result == null ? com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (personType_ != com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.UNKNOWN_PERSON_TYPE.getNumber()) {
        output.writeEnum(1, personType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (personType_ != com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.UNKNOWN_PERSON_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, personType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Persontypeenum.PersonTypePb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Persontypeenum.PersonTypePb other = (com.prod.app.protobuff.Persontypeenum.PersonTypePb) obj;

      if (personType_ != other.personType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERSONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + personType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Persontypeenum.PersonTypePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.PersonTypePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.PersonTypePb)
        com.prod.app.protobuff.Persontypeenum.PersonTypePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Persontypeenum.internal_static_com_prod_app_protobuff_PersonTypePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Persontypeenum.internal_static_com_prod_app_protobuff_PersonTypePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Persontypeenum.PersonTypePb.class, com.prod.app.protobuff.Persontypeenum.PersonTypePb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Persontypeenum.PersonTypePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        personType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Persontypeenum.internal_static_com_prod_app_protobuff_PersonTypePb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Persontypeenum.PersonTypePb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Persontypeenum.PersonTypePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Persontypeenum.PersonTypePb build() {
        com.prod.app.protobuff.Persontypeenum.PersonTypePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Persontypeenum.PersonTypePb buildPartial() {
        com.prod.app.protobuff.Persontypeenum.PersonTypePb result = new com.prod.app.protobuff.Persontypeenum.PersonTypePb(this);
        result.personType_ = personType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Persontypeenum.PersonTypePb) {
          return mergeFrom((com.prod.app.protobuff.Persontypeenum.PersonTypePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Persontypeenum.PersonTypePb other) {
        if (other == com.prod.app.protobuff.Persontypeenum.PersonTypePb.getDefaultInstance()) return this;
        if (other.personType_ != 0) {
          setPersonTypeValue(other.getPersonTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Persontypeenum.PersonTypePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Persontypeenum.PersonTypePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int personType_ = 0;
      /**
       * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
       */
      public int getPersonTypeValue() {
        return personType_;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
       */
      public Builder setPersonTypeValue(int value) {
        personType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
       */
      public com.prod.app.protobuff.Persontypeenum.PersonTypeEnum getPersonType() {
        @SuppressWarnings("deprecation")
        com.prod.app.protobuff.Persontypeenum.PersonTypeEnum result = com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.valueOf(personType_);
        return result == null ? com.prod.app.protobuff.Persontypeenum.PersonTypeEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
       */
      public Builder setPersonType(com.prod.app.protobuff.Persontypeenum.PersonTypeEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        personType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.PersonTypeEnum personType = 1;</code>
       */
      public Builder clearPersonType() {
        
        personType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.PersonTypePb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.PersonTypePb)
    private static final com.prod.app.protobuff.Persontypeenum.PersonTypePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Persontypeenum.PersonTypePb();
    }

    public static com.prod.app.protobuff.Persontypeenum.PersonTypePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonTypePb>
        PARSER = new com.google.protobuf.AbstractParser<PersonTypePb>() {
      @java.lang.Override
      public PersonTypePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonTypePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonTypePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonTypePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Persontypeenum.PersonTypePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_PersonTypePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_PersonTypePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024persontypeenum.proto\022\026com.prod.app.pro" +
      "tobuff\"J\n\014PersonTypePb\022:\n\npersonType\030\001 \001" +
      "(\0162&.com.prod.app.protobuff.PersonTypeEn" +
      "um*C\n\016PersonTypeEnum\022\027\n\023UNKNOWN_PERSON_T" +
      "YPE\020\000\022\n\n\006WORKER\020\001\022\014\n\010CONSUMER\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_prod_app_protobuff_PersonTypePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_PersonTypePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_PersonTypePb_descriptor,
        new java.lang.String[] { "PersonType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
