// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responsestatusenum.proto

package com.prod.app.protobuff;

public final class Responsestatusenum {
  private Responsestatusenum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.prod.app.protobuff.ResponseSatusEnum}
   */
  public enum ResponseSatusEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_RESPONSE_STATUS = 0;</code>
     */
    UNKNOWN_RESPONSE_STATUS(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>FAILED = 2;</code>
     */
    FAILED(2),
    /**
     * <code>ERROR = 3;</code>
     */
    ERROR(3),
    /**
     * <code>USER_EXIST = 4;</code>
     */
    USER_EXIST(4),
    /**
     * <code>USER_NOT_REGISTRED = 5;</code>
     */
    USER_NOT_REGISTRED(5),
    /**
     * <code>UNEXP_ERROR = 6;</code>
     */
    UNEXP_ERROR(6),
    /**
     * <code>INVALID_CREDENTIALS = 7;</code>
     */
    INVALID_CREDENTIALS(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_RESPONSE_STATUS = 0;</code>
     */
    public static final int UNKNOWN_RESPONSE_STATUS_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAILED = 2;</code>
     */
    public static final int FAILED_VALUE = 2;
    /**
     * <code>ERROR = 3;</code>
     */
    public static final int ERROR_VALUE = 3;
    /**
     * <code>USER_EXIST = 4;</code>
     */
    public static final int USER_EXIST_VALUE = 4;
    /**
     * <code>USER_NOT_REGISTRED = 5;</code>
     */
    public static final int USER_NOT_REGISTRED_VALUE = 5;
    /**
     * <code>UNEXP_ERROR = 6;</code>
     */
    public static final int UNEXP_ERROR_VALUE = 6;
    /**
     * <code>INVALID_CREDENTIALS = 7;</code>
     */
    public static final int INVALID_CREDENTIALS_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseSatusEnum valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseSatusEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_RESPONSE_STATUS;
        case 1: return SUCCESS;
        case 2: return FAILED;
        case 3: return ERROR;
        case 4: return USER_EXIST;
        case 5: return USER_NOT_REGISTRED;
        case 6: return UNEXP_ERROR;
        case 7: return INVALID_CREDENTIALS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseSatusEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseSatusEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseSatusEnum>() {
            public ResponseSatusEnum findValueByNumber(int number) {
              return ResponseSatusEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.prod.app.protobuff.Responsestatusenum.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseSatusEnum[] VALUES = values();

    public static ResponseSatusEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseSatusEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.prod.app.protobuff.ResponseSatusEnum)
  }

  public interface ResponseTypePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.ResponseTypePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
     */
    int getStatusTypeValue();
    /**
     * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
     */
    com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum getStatusType();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.ResponseTypePb}
   */
  public  static final class ResponseTypePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.ResponseTypePb)
      ResponseTypePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseTypePb.newBuilder() to construct.
    private ResponseTypePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseTypePb() {
      statusType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseTypePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseTypePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              statusType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Responsestatusenum.internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Responsestatusenum.internal_static_com_prod_app_protobuff_ResponseTypePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.class, com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.Builder.class);
    }

    public static final int STATUSTYPE_FIELD_NUMBER = 1;
    private int statusType_;
    /**
     * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
     */
    public int getStatusTypeValue() {
      return statusType_;
    }
    /**
     * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
     */
    public com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum getStatusType() {
      @SuppressWarnings("deprecation")
      com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum result = com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.valueOf(statusType_);
      return result == null ? com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusType_ != com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.UNKNOWN_RESPONSE_STATUS.getNumber()) {
        output.writeEnum(1, statusType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusType_ != com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.UNKNOWN_RESPONSE_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, statusType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Responsestatusenum.ResponseTypePb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Responsestatusenum.ResponseTypePb other = (com.prod.app.protobuff.Responsestatusenum.ResponseTypePb) obj;

      if (statusType_ != other.statusType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + statusType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Responsestatusenum.ResponseTypePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.ResponseTypePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.ResponseTypePb)
        com.prod.app.protobuff.Responsestatusenum.ResponseTypePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Responsestatusenum.internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Responsestatusenum.internal_static_com_prod_app_protobuff_ResponseTypePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.class, com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Responsestatusenum.internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Responsestatusenum.ResponseTypePb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Responsestatusenum.ResponseTypePb build() {
        com.prod.app.protobuff.Responsestatusenum.ResponseTypePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Responsestatusenum.ResponseTypePb buildPartial() {
        com.prod.app.protobuff.Responsestatusenum.ResponseTypePb result = new com.prod.app.protobuff.Responsestatusenum.ResponseTypePb(this);
        result.statusType_ = statusType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Responsestatusenum.ResponseTypePb) {
          return mergeFrom((com.prod.app.protobuff.Responsestatusenum.ResponseTypePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Responsestatusenum.ResponseTypePb other) {
        if (other == com.prod.app.protobuff.Responsestatusenum.ResponseTypePb.getDefaultInstance()) return this;
        if (other.statusType_ != 0) {
          setStatusTypeValue(other.getStatusTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Responsestatusenum.ResponseTypePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Responsestatusenum.ResponseTypePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusType_ = 0;
      /**
       * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
       */
      public int getStatusTypeValue() {
        return statusType_;
      }
      /**
       * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
       */
      public Builder setStatusTypeValue(int value) {
        statusType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
       */
      public com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum getStatusType() {
        @SuppressWarnings("deprecation")
        com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum result = com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.valueOf(statusType_);
        return result == null ? com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
       */
      public Builder setStatusType(com.prod.app.protobuff.Responsestatusenum.ResponseSatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        statusType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.ResponseSatusEnum statusType = 1;</code>
       */
      public Builder clearStatusType() {
        
        statusType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.ResponseTypePb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.ResponseTypePb)
    private static final com.prod.app.protobuff.Responsestatusenum.ResponseTypePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Responsestatusenum.ResponseTypePb();
    }

    public static com.prod.app.protobuff.Responsestatusenum.ResponseTypePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseTypePb>
        PARSER = new com.google.protobuf.AbstractParser<ResponseTypePb>() {
      @java.lang.Override
      public ResponseTypePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseTypePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseTypePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseTypePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Responsestatusenum.ResponseTypePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_ResponseTypePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030responsestatusenum.proto\022\026com.prod.app" +
      ".protobuff\"O\n\016ResponseTypePb\022=\n\nstatusTy" +
      "pe\030\001 \001(\0162).com.prod.app.protobuff.Respon" +
      "seSatusEnum*\246\001\n\021ResponseSatusEnum\022\033\n\027UNK" +
      "NOWN_RESPONSE_STATUS\020\000\022\013\n\007SUCCESS\020\001\022\n\n\006F" +
      "AILED\020\002\022\t\n\005ERROR\020\003\022\016\n\nUSER_EXIST\020\004\022\026\n\022US" +
      "ER_NOT_REGISTRED\020\005\022\017\n\013UNEXP_ERROR\020\006\022\027\n\023I" +
      "NVALID_CREDENTIALS\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_ResponseTypePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_ResponseTypePb_descriptor,
        new java.lang.String[] { "StatusType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
