// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time.proto

package com.prod.app.protobuff;

public final class Time {
  private Time() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.prod.app.protobuff.TimeZoneEnum}
   */
  public enum TimeZoneEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_TIME_ZONE = 0;</code>
     */
    UNKNOWN_TIME_ZONE(0),
    /**
     * <code>IST = 1;</code>
     */
    IST(1),
    /**
     * <code>UTC = 2;</code>
     */
    UTC(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_TIME_ZONE = 0;</code>
     */
    public static final int UNKNOWN_TIME_ZONE_VALUE = 0;
    /**
     * <code>IST = 1;</code>
     */
    public static final int IST_VALUE = 1;
    /**
     * <code>UTC = 2;</code>
     */
    public static final int UTC_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TimeZoneEnum valueOf(int value) {
      return forNumber(value);
    }

    public static TimeZoneEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_TIME_ZONE;
        case 1: return IST;
        case 2: return UTC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TimeZoneEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TimeZoneEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TimeZoneEnum>() {
            public TimeZoneEnum findValueByNumber(int number) {
              return TimeZoneEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.prod.app.protobuff.Time.getDescriptor().getEnumTypes().get(0);
    }

    private static final TimeZoneEnum[] VALUES = values();

    public static TimeZoneEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TimeZoneEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.prod.app.protobuff.TimeZoneEnum)
  }

  public interface TimePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.prod.app.protobuff.TimePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string date = 1;</code>
     */
    java.lang.String getDate();
    /**
     * <code>string date = 1;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>string month = 2;</code>
     */
    java.lang.String getMonth();
    /**
     * <code>string month = 2;</code>
     */
    com.google.protobuf.ByteString
        getMonthBytes();

    /**
     * <code>string year = 3;</code>
     */
    java.lang.String getYear();
    /**
     * <code>string year = 3;</code>
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>int64 milliseconds = 4;</code>
     */
    long getMilliseconds();

    /**
     * <code>string formattedDate = 5;</code>
     */
    java.lang.String getFormattedDate();
    /**
     * <code>string formattedDate = 5;</code>
     */
    com.google.protobuf.ByteString
        getFormattedDateBytes();

    /**
     * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
     */
    int getTimezoneValue();
    /**
     * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
     */
    com.prod.app.protobuff.Time.TimeZoneEnum getTimezone();
  }
  /**
   * Protobuf type {@code com.prod.app.protobuff.TimePb}
   */
  public  static final class TimePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.prod.app.protobuff.TimePb)
      TimePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimePb.newBuilder() to construct.
    private TimePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimePb() {
      date_ = "";
      month_ = "";
      year_ = "";
      formattedDate_ = "";
      timezone_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              month_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 32: {

              milliseconds_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              formattedDate_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              timezone_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.prod.app.protobuff.Time.internal_static_com_prod_app_protobuff_TimePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.prod.app.protobuff.Time.internal_static_com_prod_app_protobuff_TimePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.prod.app.protobuff.Time.TimePb.class, com.prod.app.protobuff.Time.TimePb.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private volatile java.lang.Object month_;
    /**
     * <code>string month = 2;</code>
     */
    public java.lang.String getMonth() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        month_ = s;
        return s;
      }
    }
    /**
     * <code>string month = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMonthBytes() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object year_;
    /**
     * <code>string year = 3;</code>
     */
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 3;</code>
     */
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MILLISECONDS_FIELD_NUMBER = 4;
    private long milliseconds_;
    /**
     * <code>int64 milliseconds = 4;</code>
     */
    public long getMilliseconds() {
      return milliseconds_;
    }

    public static final int FORMATTEDDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object formattedDate_;
    /**
     * <code>string formattedDate = 5;</code>
     */
    public java.lang.String getFormattedDate() {
      java.lang.Object ref = formattedDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formattedDate_ = s;
        return s;
      }
    }
    /**
     * <code>string formattedDate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFormattedDateBytes() {
      java.lang.Object ref = formattedDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formattedDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEZONE_FIELD_NUMBER = 6;
    private int timezone_;
    /**
     * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
     */
    public int getTimezoneValue() {
      return timezone_;
    }
    /**
     * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
     */
    public com.prod.app.protobuff.Time.TimeZoneEnum getTimezone() {
      @SuppressWarnings("deprecation")
      com.prod.app.protobuff.Time.TimeZoneEnum result = com.prod.app.protobuff.Time.TimeZoneEnum.valueOf(timezone_);
      return result == null ? com.prod.app.protobuff.Time.TimeZoneEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (!getMonthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, month_);
      }
      if (!getYearBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, year_);
      }
      if (milliseconds_ != 0L) {
        output.writeInt64(4, milliseconds_);
      }
      if (!getFormattedDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, formattedDate_);
      }
      if (timezone_ != com.prod.app.protobuff.Time.TimeZoneEnum.UNKNOWN_TIME_ZONE.getNumber()) {
        output.writeEnum(6, timezone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (!getMonthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, month_);
      }
      if (!getYearBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, year_);
      }
      if (milliseconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, milliseconds_);
      }
      if (!getFormattedDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, formattedDate_);
      }
      if (timezone_ != com.prod.app.protobuff.Time.TimeZoneEnum.UNKNOWN_TIME_ZONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, timezone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.prod.app.protobuff.Time.TimePb)) {
        return super.equals(obj);
      }
      com.prod.app.protobuff.Time.TimePb other = (com.prod.app.protobuff.Time.TimePb) obj;

      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getMonth()
          .equals(other.getMonth())) return false;
      if (!getYear()
          .equals(other.getYear())) return false;
      if (getMilliseconds()
          != other.getMilliseconds()) return false;
      if (!getFormattedDate()
          .equals(other.getFormattedDate())) return false;
      if (timezone_ != other.timezone_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + MILLISECONDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMilliseconds());
      hash = (37 * hash) + FORMATTEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getFormattedDate().hashCode();
      hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
      hash = (53 * hash) + timezone_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Time.TimePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Time.TimePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.prod.app.protobuff.Time.TimePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.prod.app.protobuff.Time.TimePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.prod.app.protobuff.TimePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.prod.app.protobuff.TimePb)
        com.prod.app.protobuff.Time.TimePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.prod.app.protobuff.Time.internal_static_com_prod_app_protobuff_TimePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.prod.app.protobuff.Time.internal_static_com_prod_app_protobuff_TimePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.prod.app.protobuff.Time.TimePb.class, com.prod.app.protobuff.Time.TimePb.Builder.class);
      }

      // Construct using com.prod.app.protobuff.Time.TimePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        date_ = "";

        month_ = "";

        year_ = "";

        milliseconds_ = 0L;

        formattedDate_ = "";

        timezone_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.prod.app.protobuff.Time.internal_static_com_prod_app_protobuff_TimePb_descriptor;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Time.TimePb getDefaultInstanceForType() {
        return com.prod.app.protobuff.Time.TimePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.prod.app.protobuff.Time.TimePb build() {
        com.prod.app.protobuff.Time.TimePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.prod.app.protobuff.Time.TimePb buildPartial() {
        com.prod.app.protobuff.Time.TimePb result = new com.prod.app.protobuff.Time.TimePb(this);
        result.date_ = date_;
        result.month_ = month_;
        result.year_ = year_;
        result.milliseconds_ = milliseconds_;
        result.formattedDate_ = formattedDate_;
        result.timezone_ = timezone_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.prod.app.protobuff.Time.TimePb) {
          return mergeFrom((com.prod.app.protobuff.Time.TimePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.prod.app.protobuff.Time.TimePb other) {
        if (other == com.prod.app.protobuff.Time.TimePb.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (!other.getMonth().isEmpty()) {
          month_ = other.month_;
          onChanged();
        }
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (other.getMilliseconds() != 0L) {
          setMilliseconds(other.getMilliseconds());
        }
        if (!other.getFormattedDate().isEmpty()) {
          formattedDate_ = other.formattedDate_;
          onChanged();
        }
        if (other.timezone_ != 0) {
          setTimezoneValue(other.getTimezoneValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.prod.app.protobuff.Time.TimePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.prod.app.protobuff.Time.TimePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 1;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 1;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 1;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object month_ = "";
      /**
       * <code>string month = 2;</code>
       */
      public java.lang.String getMonth() {
        java.lang.Object ref = month_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          month_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string month = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMonthBytes() {
        java.lang.Object ref = month_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          month_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string month = 2;</code>
       */
      public Builder setMonth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string month = 2;</code>
       */
      public Builder clearMonth() {
        
        month_ = getDefaultInstance().getMonth();
        onChanged();
        return this;
      }
      /**
       * <code>string month = 2;</code>
       */
      public Builder setMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        month_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>string year = 3;</code>
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string year = 3;</code>
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 3;</code>
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 3;</code>
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 3;</code>
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private long milliseconds_ ;
      /**
       * <code>int64 milliseconds = 4;</code>
       */
      public long getMilliseconds() {
        return milliseconds_;
      }
      /**
       * <code>int64 milliseconds = 4;</code>
       */
      public Builder setMilliseconds(long value) {
        
        milliseconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 milliseconds = 4;</code>
       */
      public Builder clearMilliseconds() {
        
        milliseconds_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object formattedDate_ = "";
      /**
       * <code>string formattedDate = 5;</code>
       */
      public java.lang.String getFormattedDate() {
        java.lang.Object ref = formattedDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          formattedDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string formattedDate = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFormattedDateBytes() {
        java.lang.Object ref = formattedDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          formattedDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string formattedDate = 5;</code>
       */
      public Builder setFormattedDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        formattedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string formattedDate = 5;</code>
       */
      public Builder clearFormattedDate() {
        
        formattedDate_ = getDefaultInstance().getFormattedDate();
        onChanged();
        return this;
      }
      /**
       * <code>string formattedDate = 5;</code>
       */
      public Builder setFormattedDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        formattedDate_ = value;
        onChanged();
        return this;
      }

      private int timezone_ = 0;
      /**
       * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
       */
      public int getTimezoneValue() {
        return timezone_;
      }
      /**
       * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
       */
      public Builder setTimezoneValue(int value) {
        timezone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
       */
      public com.prod.app.protobuff.Time.TimeZoneEnum getTimezone() {
        @SuppressWarnings("deprecation")
        com.prod.app.protobuff.Time.TimeZoneEnum result = com.prod.app.protobuff.Time.TimeZoneEnum.valueOf(timezone_);
        return result == null ? com.prod.app.protobuff.Time.TimeZoneEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
       */
      public Builder setTimezone(com.prod.app.protobuff.Time.TimeZoneEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        timezone_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.prod.app.protobuff.TimeZoneEnum timezone = 6;</code>
       */
      public Builder clearTimezone() {
        
        timezone_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.prod.app.protobuff.TimePb)
    }

    // @@protoc_insertion_point(class_scope:com.prod.app.protobuff.TimePb)
    private static final com.prod.app.protobuff.Time.TimePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.prod.app.protobuff.Time.TimePb();
    }

    public static com.prod.app.protobuff.Time.TimePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimePb>
        PARSER = new com.google.protobuf.AbstractParser<TimePb>() {
      @java.lang.Override
      public TimePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.prod.app.protobuff.Time.TimePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_prod_app_protobuff_TimePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_prod_app_protobuff_TimePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntime.proto\022\026com.prod.app.protobuff\"\230\001\n" +
      "\006TimePb\022\014\n\004date\030\001 \001(\t\022\r\n\005month\030\002 \001(\t\022\014\n\004" +
      "year\030\003 \001(\t\022\024\n\014milliseconds\030\004 \001(\003\022\025\n\rform" +
      "attedDate\030\005 \001(\t\0226\n\010timezone\030\006 \001(\0162$.com." +
      "prod.app.protobuff.TimeZoneEnum*7\n\014TimeZ" +
      "oneEnum\022\025\n\021UNKNOWN_TIME_ZONE\020\000\022\007\n\003IST\020\001\022" +
      "\007\n\003UTC\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_prod_app_protobuff_TimePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_prod_app_protobuff_TimePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_prod_app_protobuff_TimePb_descriptor,
        new java.lang.String[] { "Date", "Month", "Year", "Milliseconds", "FormattedDate", "Timezone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
